sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:

  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18
    compiler: ": #GHC 7.8.4"
    addons: {apt: {packages: [cabal-install-1.18,happy-1.19.5,ghc-7.8.4], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    compiler: ": #GHC 7.10.3"
    addons: {apt: {packages: [cabal-install-1.22,happy-1.19.5,ghc-7.10.3], sources: [hvr-ghc]}}

  # - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24
  #   compiler: ": #GHC 8.0.2"
  #   addons: {apt: {packages: [cabal-install-1.24,happy-1.19.5,ghc-8.0.2], sources: [hvr-ghc]}}

  # - env: BUILD=cabal GHCVER=8.2.1 CABALVER=1.24
  #   compiler: ": #GHC 8.2.1"
  #   addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.1], sources: [hvr-ghc]}}

  - env: BUILD=stack ARGS="" # --resolver lts-8"
    compiler: ": #stack 7.10.3"
    addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

  # - env: BUILD=stack ARGS="--stack-yaml stack.yaml.8" # --resolver lts-8"
  #   compiler: ": #stack 8.0.2"
  #   addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}
 
  fast_finish: true

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
- export PATH=$PATH:/opt/happy/1.19.5/bin/:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$HOME/.cabal/bin

# Download and unpack the stack executable
- |
  if [[ $BUILD == "stack" ]]; then
    mkdir -p ~/.local/bin
    if [ `uname` = "Darwin" ]
    then
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  fi

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack --no-terminal config set system-ghc --global true
      stack --no-terminal install hsc2hs
      stack --no-terminal setup
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
      cabal install hsc2hs
      cabal install --only-dependencies --enable-tests --enable-benchmarks
      ;;
  esac

script:
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack --no-terminal $ARGS test > tst
      # > tst # --haddock --no-haddock-deps --ghc-options="-O0 -Wall -fno-warn-unused-do-bind -Werror"
      ;;
    cabal)
      cabal sdist --output-directory=sourcedist && \
      cd sourcedist && \
      cabal configure --enable-tests --enable-benchmarks -v2 && \
      echo "[BUILD" && \
      cabal build && \
      echo "BUILD]" && \
      cabal test > tst
      ;;
  esac
