resolver: lts-6.22
#resolver: lts-7.4

packages:
- '.'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
